basePath: /api/v1
definitions:
  binder.ApplyJobRequest:
    properties:
      jobID:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
  binder.ApproveApplicantRequest:
    properties:
      jobApplicantID:
        type: string
    type: object
  binder.CreateCategoryRequest:
    properties:
      icon:
        type: string
      title:
        type: string
    type: object
  binder.CreateJobRequest:
    properties:
      category_id:
        type: string
      company:
        type: string
      description:
        type: string
      location:
        type: string
      logo:
        type: string
      salary:
        type: number
      status:
        type: string
      title:
        type: string
    type: object
  binder.CreateUserRequest:
    properties:
      address:
        example: 123 Main St
        type: string
      email:
        example: john.doe@example.com
        type: string
      gender:
        example: male
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: password123
        type: string
      phone_number:
        example: 123-456-7890
        type: string
      role:
        example: applicant
        type: string
    type: object
  binder.DeleteCategoryRequest:
    properties:
      id:
        type: string
    type: object
  binder.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  binder.UpdateCategoryRequest:
    properties:
      icon:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  binder.UpdateJobRequest:
    properties:
      category_id:
        type: string
      client_id:
        type: string
      company:
        type: string
      description:
        type: string
      id:
        type: string
      location:
        type: string
      logo:
        type: string
      salary:
        type: number
      status:
        type: string
      title:
        type: string
    type: object
  binder.UpdateUserRequest:
    properties:
      address:
        type: string
      email:
        type: string
      gender:
        type: string
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  binder.UserFindByIDRequest:
    properties:
      id:
        type: string
    required:
    - id
    type: object
  binder.WithdrawJobRequest:
    properties:
      jobApplicantID:
        type: string
    type: object
  response.Meta:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.Response:
    properties:
      data: {}
      meta:
        $ref: '#/definitions/response.Meta'
    type: object
host: 103.157.26.216:8080
info:
  contact:
    email: davidafdal7@gmail.com
    name: David Afdal Kaizar Mutahadi
    url: https://davidafdal.github.io/web-portofolio/
  description: This is a Rest API job finder server.
  termsOfService: http://swagger.io/terms/
  title: Job Finder App API
  version: "1.0"
paths:
  /categories:
    delete:
      consumes:
      - application/json
      description: Delete a category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: Delete Category Request
        in: body
        name: deleteCategory
        required: true
        schema:
          $ref: '#/definitions/binder.DeleteCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Delete a category
      tags:
      - categories
    get:
      description: Get all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Create Category Request
        in: body
        name: createCategory
        required: true
        schema:
          $ref: '#/definitions/binder.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Create a new category
      tags:
      - categories
  /categories/{id}:
    get:
      description: Get a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a category by ID
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update a category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Category Request
        in: body
        name: updateCategory
        required: true
        schema:
          $ref: '#/definitions/binder.UpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Update a category
      tags:
      - categories
  /jobs:
    get:
      description: Get all jobs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get all jobs
      tags:
      - jobs
    post:
      description: Create a new job
      parameters:
      - description: Create Job Request
        in: body
        name: job
        required: true
        schema:
          $ref: '#/definitions/binder.CreateJobRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Create a new job
      tags:
      - jobs
  /jobs/{JobApplicantID}/applications:
    get:
      consumes:
      - application/json
      description: Find job applicant by ID
      parameters:
      - description: Job Applicant ID
        in: path
        name: JobApplicantID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Find job applicant by ID
      tags:
      - job-applicants
  /jobs/{JobApplicantID}/approve:
    post:
      consumes:
      - application/json
      description: Approve job applicant
      parameters:
      - description: Job Applicant ID
        in: path
        name: JobApplicantID
        required: true
        type: string
      - description: Approve Applicant Request
        in: body
        name: approveApplicant
        required: true
        schema:
          $ref: '#/definitions/binder.ApproveApplicantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Approve job applicant
      tags:
      - job-applicants
  /jobs/{JobApplicantID}/withdraw:
    post:
      consumes:
      - application/json
      description: Withdraw job application
      parameters:
      - description: Job Applicant ID
        in: path
        name: JobApplicantID
        required: true
        type: string
      - description: Withdraw Job Request
        in: body
        name: withdrawJob
        required: true
        schema:
          $ref: '#/definitions/binder.WithdrawJobRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Withdraw job application
      tags:
      - job-applicants
  /jobs/{id}:
    delete:
      description: Delete a job
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Delete a job
      tags:
      - jobs
    get:
      description: Get job by ID
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get job by ID
      tags:
      - jobs
    put:
      description: Update a job
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Job Request
        in: body
        name: job
        required: true
        schema:
          $ref: '#/definitions/binder.UpdateJobRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Update a job
      tags:
      - jobs
  /jobs/{jobID}/apply:
    post:
      consumes:
      - application/json
      description: Apply for a job
      parameters:
      - description: Job ID
        in: path
        name: jobID
        required: true
        type: string
      - description: Apply Job Request
        in: body
        name: applyJob
        required: true
        schema:
          $ref: '#/definitions/binder.ApplyJobRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Apply for a job
      tags:
      - job-applicants
  /jobs/applied:
    get:
      description: Get applied jobs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Get applied jobs
      tags:
      - jobs
  /jobs/shared:
    get:
      description: Get shared jobs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Get shared jobs
      tags:
      - jobs
  /login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/binder.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
      summary: Login
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Create User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/binder.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create User
      tags:
      - auth
  /users:
    delete:
      consumes:
      - application/json
      description: Delete an existing user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Delete User
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get All Users
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update an existing user
      parameters:
      - description: Update User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/binder.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Update User
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      parameters:
      - description: Find User by ID Reques
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/binder.UserFindByIDRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get User By ID
      tags:
      - users
  /users/profile:
    get:
      consumes:
      - application/json
      description: Get the profile of the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Get User Profile
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
