name: CI
on:
  push:
    branches: ["stagging"]

jobs:
  build:
    environment: stagging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/finder-job:latest

  deployment:
    needs: build
    environment: stagging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            whoami
            docker stop finder-job || true && docker rm finder-job || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/finder-job:latest
            docker run -d -p 1213:1213 --name ${{ vars.CONTAINER_NAME }} ${{ secrets.DOCKER_USERNAME }}/finder-job:latest
